Update Astro template (#38)

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -12,57 +12,83 @@ ARG UID=1001
 # --
 # Upstream images
 
-FROM node:22-slim AS node_upstream
+FROM node:24-slim AS node_upstream
 FROM nginx:1.29-alpine AS nginx_upstream
 
 
 # --
-# Base image
+# Base stage
 
-FROM node_upstream AS app_base
+FROM node_upstream AS node_base
 
 # Set app directory
 WORKDIR /app
 
+# Set home directory for cache
+ENV HOME=/tmp
+
 
 # --
-# Build base image
+# Build base stage
 
-FROM app_base AS app_build_base
+FROM node_base AS node_build_base
 
 # Install pnpm
-RUN --mount=type=cache,target=~/.npm \
+RUN --mount=type=cache,id=npm,target=/root/.npm \
 	npm install -g pnpm
 
 
 # --
-# Build dev image
+# Deps base stage
 
-FROM app_build_base AS app_build_dev
+FROM node_build_base AS deps_base
 
-# Copy app build configuration
-COPY --link \
-	./app/package.json \
-	./app/pnpm-lock.yaml \
-	./
+# Copy build configuration
+COPY --link ./app/package.json ./app/pnpm-lock.yaml ./
 
-# Install app development dependencies
+
+# --
+# Deps dev stage
+
+FROM deps_base AS deps_dev
+
+# Install development dependencies
 RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
 	pnpm install --frozen-lockfile
+
+# Create Astro runtime directory
+RUN mkdir -p ./.astro
 
 
 # --
 # CLI image
 
-FROM app_build_base AS app_cli
+FROM node_build_base AS app_cli
 
+# Build arguments
 ARG UID
 
-# Use temporary directory as home
-ENV HOME=/tmp
+# Install sudo
+# (hadolint: Ignore non-pinned apt package version)
+# hadolint ignore=DL3008
+RUN --mount=type=cache,sharing=locked,id=apt-cache,target=/var/cache/apt \
+	--mount=type=cache,sharing=locked,id=apt-lib,target=/var/lib/apt \
+	apt-get update && \
+	apt-get install -y --no-install-recommends sudo && \
+	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 
-# Run as non-root user
-USER ${UID}:0
+# Create user 'user' in group 'root' & 'sudo'
+# (hadolint: Ignore unchecked pipe failures)
+# hadolint ignore=DL4006
+RUN USERNAME="$(getent passwd "${UID}" 2>/dev/null | cut -d: -f1 || true)"; \
+	if [ -z "${USERNAME}" ]; then \
+		useradd -lm -u "${UID}" -U -G 0,sudo user; \
+	else \
+		usermod -a -G 0,sudo "${USERNAME}"; \
+	fi
+
+# Run as created non-root user
+USER ${UID}
 
 # Mount source code
 VOLUME /app
@@ -74,33 +100,112 @@ CMD [ "--help" ]
 
 
 # --
+# Lint image
+
+FROM node_build_base AS app_lint
+
+# Build arguments
+ARG UID
+
+# Run as non-root user
+USER ${UID}:0
+
+CMD [ "sh", "-c", "exit 0" ]
+
+
+# --
+# Test base stage
+
+FROM node_build_base AS test_base
+
+# Build arguments
+ARG UID
+
+# Set runtime environment
+ENV APP_ENV=test
+
+# Copy development dependencies
+ENV NODE_ENV=development
+COPY --from=deps_dev --link --chown="${UID}:0" /app/.astro/ ./.astro/
+COPY --from=deps_dev --link --chown="${UID}:0" /app/node_modules/ ./node_modules/
+
+
+# --
+# Test unit image
+
+FROM test_base AS test_unit
+
+# Build arguments
+ARG UID
+
+# Copy source code
+RUN chown "${UID}:0" .
+COPY --link --chown="${UID}:0" ./app/ ./
+
+# Run as non-root user
+USER ${UID}:0
+
+CMD [ "sh", "-c", "pnpm run test:vitest" ]
+
+
+# --
+# Test E2E image
+
+FROM test_base AS test_e2e
+
+# Build arguments
+ARG UID
+
+# Install Playwright dependencies
+ENV PLAYWRIGHT_BROWSERS_PATH=/etc/playwright/browsers
+COPY --from=deps_dev --link --chown="${UID}:0" /app/package.json /app/pnpm-lock.yaml ./
+RUN pnpm exec playwright install --with-deps
+
+# Copy source code
+RUN chown "${UID}:0" .
+COPY --link --chown="${UID}:0" ./app/ ./
+
+# Build application
+RUN pnpm run build-only
+
+# Run as non-root user
+USER ${UID}:0
+
+CMD [ "sh", "-c", "pnpm run test:playwright --output /tmp/playwright/test-results" ]
+
+
+# --
 # Dev image
 
-FROM app_base AS app_dev
+FROM node_build_base AS app_dev
 
+# Build arguments
 ARG UID
 
 # Set runtime environment
 ENV APP_ENV=dev
-ENV NODE_ENV=development
 
-# Copy app development dependencies
-COPY --link --from=app_build_dev --chown="${UID}:0" /app/node_modules ./node_modules
+# Copy development dependencies
+ENV NODE_ENV=development
+COPY --from=deps_dev --link --chown="${UID}:0" /app/.astro/ ./.astro/
+COPY --from=deps_dev --link --chown="${UID}:0" /app/node_modules/ ./node_modules/
 
 # Copy source code
-COPY --link --chown="${UID}:0" ./app .
-RUN mkdir -p ./.astro && chown -R "${UID}:0" ./.astro
+RUN chown "${UID}:0" .
+COPY --link --chown="${UID}:0" ./app/ ./
 
 # Create user 'user' in group 'root'
-RUN USERNAME="$(getent passwd "${UID}" | cut -d: -f1)"; \
+# (hadolint: Ignore unchecked pipe failures)
+# hadolint ignore=DL4006
+RUN USERNAME="$(getent passwd "${UID}" 2>/dev/null | cut -d: -f1 || true)"; \
 	if [ -z "${USERNAME}" ]; then \
-		useradd -lm -u "${UID}" -g "${UID}" -G 0 user; \
+		useradd -lm -u "${UID}" -U -G 0 user; \
 	else \
 		usermod -a -G 0 "${USERNAME}"; \
 	fi
 
-# Run as non-root user
-USER ${UID}:0
+# Run as created non-root user
+USER ${UID}
 
 # Set exposed port
 ARG PORT=8080
@@ -108,38 +213,51 @@ ENV PORT=${PORT}
 EXPOSE ${PORT}
 
 # Start development server
-CMD [ "sh", "-c", "npm run dev -- --host --port \"${PORT}\"" ]
+CMD [ "sh", "-c", "pnpm run dev --host --port \"${PORT}\"" ]
 
 
 # --
-# Prod build image
+# Prod build stage
 
-FROM app_base AS app_prod_build
+FROM node_build_base AS app_prod_build
 
+# Build arguments
 ARG UID
 
 # Set runtime environment
 ENV APP_ENV=prod
-ENV NODE_ENV=production
 
-# Copy app development dependencies
-COPY --link --from=app_build_dev --chown="${UID}:0" /app/node_modules ./node_modules
+# Copy development dependencies
+ENV NODE_ENV=development
+COPY --from=deps_dev --link --chown="${UID}:0" /app/node_modules/ ./node_modules/
 
 # Copy source code
-COPY --link --chown="${UID}:0" ./app .
+COPY --link --chown="${UID}:0" ./app/ ./
 
-# Set client environment variables
-ARG GITHUB_REPOSITORY_URL=""
+# Set app environment variables
+# : Deployment configuration
+ARG GITHUB_REPOSITORY_URL=''
 ENV GITHUB_REPOSITORY_URL=${GITHUB_REPOSITORY_URL}
-ARG GITHUB_SHA=""
+ARG GITHUB_SHA=''
 ENV GITHUB_SHA=${GITHUB_SHA}
+ARG VERSION_TAG=''
+ENV VERSION_TAG=${VERSION_TAG}
+# : Astro configuration
+ARG ASTRO_SITE_URL=''
+ENV ASTRO_SITE_URL=${ASTRO_SITE_URL}
+ARG ASTRO_BASE_PATH=''
+ENV ASTRO_BASE_PATH=${ASTRO_BASE_PATH}
+ARG ASTRO_ASSETS_PREFIX=''
+ENV ASTRO_ASSETS_PREFIX=${ASTRO_ASSETS_PREFIX}
+# : Application configuration
+# Add env vars for your application here.
 
 # Build application
-ARG BUILD_CHECK=true
-RUN if [ "${BUILD_CHECK}" = "true" ]; then \
-		npm run build; \
+ARG BUILD_CHECK='true'
+RUN if [ "${BUILD_CHECK}" = 'true' ]; then \
+		pnpm run build; \
 	else \
-		npm run build-only; \
+		pnpm run build-only; \
 	fi
 
 
